#!/usr/bin/env node
// Generates reference/shortcuts (EN + RU) from the app's own shortcut list:
// PreferencesWindow.ShortcutGroups in ../nota (or $NOTA_REPO). Run `npm run shortcuts` after the
// nota-shortcuts skill has brought that list up to date. Never edit the generated pages by hand.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const appRepo = path.resolve(process.env.NOTA_REPO ?? path.join(root, '../nota'));
const srcPath = 'src/managed/Nota.App/PreferencesWindow.cs';
const src = fs.readFileSync(path.join(appRepo, srcPath), 'utf8');
const version = fs.readFileSync(path.join(appRepo, 'VERSION'), 'utf8').trim();

const start = src.indexOf('ShortcutGroups =');
const end = src.indexOf('};', start);
if (start < 0 || end < 0) throw new Error('ShortcutGroups not found in ' + srcPath);
const block = src.slice(start, end);

const unescape = (s) => s.replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16))).replace(/\\"/g, '"');
const groups = [];
for (const g of block.matchAll(/\("([A-Z][^"]*)",\s*new\[\]\s*\{([\s\S]*?)\}\)/g)) {
  const rows = [...g[2].matchAll(/\("((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)"\)/g)].map((m) => [unescape(m[1]), unescape(m[2])]);
  groups.push({ title: g[1], rows });
}
if (!groups.length) throw new Error('no shortcut groups parsed');

// Same rule as PreferencesWindow.IsKeyToken: a key has no lower-case letters, or is a named key.
const named = new Set(['Space', 'Return', 'Delete', 'Tab', 'Esc']);
const seps = new Set(['/', '·', '+']);
const isKey = (t) => named.has(t) || seps.has(t) || !/[a-z]/.test(t);
const splitMods = (t) => {
  const out = [];
  let rest = t;
  while (rest.length > 1 && /^[⌘⇧⌥⌃]/.test(rest)) { out.push(rest[0]); rest = rest.slice(1); }
  out.push(rest);
  return out;
};
const esc = (s) => s.replace(/[{}<>]/g, (c) => ({ '{': '&#123;', '}': '&#125;', '<': '&lt;', '>': '&gt;' })[c]).replace(/\|/g, '\\|');
const renderKey = (key) =>
  key
    .split(/\s{2,}/)
    .map((alt) => {
      const tokens = alt.trim().split(/\s+/);
      if (!tokens.every(isKey)) return esc(alt.trim());
      return `<Kbd keys="${tokens.flatMap((t) => (seps.has(t) || named.has(t) ? [t] : splitMods(t))).join(' ')}" />`;
    })
    .join(' · ');

const sentence = (t) => t.charAt(0) + t.slice(1).toLowerCase().replace(/\bmidi\b/g, 'MIDI').replace(/\bmacos\b/g, 'macOS');
const ru = {
  FILE: 'Файл', TRANSPORT: 'Транспорт', 'ARRANGEMENT & EDITING': 'Arrangement и редактирование',
  'TRACKS (AFTER A CLICK IN THE TRACK HEADERS)': 'Треки (после щелчка по заголовкам треков)',
  'SESSION (AFTER A CLICK IN THE GRID)': 'Session (после щелчка по сетке)', 'PIANO ROLL': 'Piano roll',
  'PLAY NOTES (COMPUTER KEYBOARD)': 'Игра нотами (клавиатура компьютера)', 'BROWSER · PREVIEW': 'Браузер · предпрослушивание',
  'GAMEPAD (MACOS)': 'Геймпад (macOS)', MOUSE: 'Мышь',
};

const page = (lang) => {
  const en = lang === 'en';
  const fm = [
    '---',
    `title: "${en ? 'Keyboard shortcuts' : 'Горячие клавиши'}"`,
    `description: "${en ? 'Every keyboard shortcut and mouse gesture in Nota, grouped as on the Settings ▸ Shortcuts page.' : 'Все сочетания клавиш и жесты мыши в Nota, по группам, как на странице Settings ▸ Shortcuts.'}"`,
    'sidebar:\n  order: 1',
    `updated: "${version}"`,
    'status: done',
    `sources:\n  - ${srcPath}`,
    '---',
  ].join('\n');
  const intro = en
    ? `This page is generated from the list on **Settings ▸ Shortcuts**, so the two always match.\nShortcuts are written the macOS way: on Windows and Linux read <Kbd keys="⌘" /> as **Ctrl** and\n<Kbd keys="⌥" /> as **Alt**.`
    : `Страница собрана из списка на **Settings ▸ Shortcuts**, поэтому они всегда совпадают. Описания\nдействий — на английском, как в приложении. Сочетания записаны как в macOS: в Windows и Linux\n<Kbd keys="⌘" /> — это **Ctrl**, а <Kbd keys="⌥" /> — **Alt**.`;
  const body = groups
    .map((g) => {
      const head = en ? sentence(g.title) : ru[g.title] ?? sentence(g.title);
      const th = en ? '| Keys | Action |' : '| Клавиши | Действие |';
      return `## ${head}\n\n${th}\n|---|---|\n` + g.rows.map(([k, a]) => `| ${renderKey(k)} | ${esc(a)} |`).join('\n');
    })
    .join('\n\n');
  return `${fm}\n\n{/* Generated by scripts/shortcuts.mjs from ${srcPath} — do not edit by hand. */}\n\nimport Kbd from '@components/Kbd.astro';\n\n${intro}\n\n${body}\n`;
};

for (const [lang, dir] of [['en', ''], ['ru', 'ru/']]) {
  const file = path.join(root, 'src/content/docs', dir, 'reference/shortcuts.mdx');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, page(lang));
}
console.log(`${groups.length} groups · ${groups.reduce((n, g) => n + g.rows.length, 0)} shortcuts → reference/shortcuts (en, ru)`);
